name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm install

    - name: Dar permissão de execução ao Jest
      run: chmod +x ./node_modules/.bin/jest  

    - name: Rodar os testes
      run: npm test
